# Generated by Django 4.1.4 on 2023-02-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_vendor_shop_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
